#!/usr/bin/env bash

DRAFT_FILE="draft-ietf-roll-nsa-extension.xml"

XML2RFC_BIN=$( which xml2rfc )
if [ -z "${XML2RFC_BIN}" ]
then
    echo "Could not find xml2rfc in the PATH. Exiting."
    exit 1
fi

GREP_BIN=$( which grep )
if [ -z "${GREP_BIN}" ]
then
    echo "Could not find grep in the PATH. Exiting."
    exit 1
fi

DRAFT_BASENAME=$( grep -oE 'docName="[^"]*"' < "${DRAFT_FILE}" | grep -oE 'draft-[^"]+' )
echo "Found ${DRAFT_BASENAME}"
xml2rfc --html --v3 --out="${DRAFT_BASENAME}.html" "${DRAFT_FILE}"
xml2rfc --text --v3 --out="${DRAFT_BASENAME}.txt" "${DRAFT_FILE}"
